language: node_js
node_js:
- node
- '7'
- '6'
notifications:
  email: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install: npm install
before_script: npm run start-ldf &
script:
- npm run lint
- npm test
after_script: kill -9 $(ps aux | grep node | awk '{print $2}')
before_deploy: npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: thomas.minier@protonmail.com
  api_key: $NPM_KEY
  on:
    tags: true
    repo: Callidon/quartz-tpf
