SELECT DISTINCT ?v1 WHERE {
  {
    SERVICE <http://52.33.245.25/watDiv_100/query> {
      {
        SELECT * WHERE { <http://db.uwaterloo.ca/~galuc/wsdbm/Offer48437> <http://schema.org/eligibleRegion> ?v1. }
        LIMIT 2
      }
    }
    
  }
  UNION
  { <http://db.uwaterloo.ca/~galuc/wsdbm/Offer48437> <http://schema.org/eligibleRegion> ?v1. }
}